name: Build and Deploy to MonsterASP

on:
  push:
    branches: [ "development" ]

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore and Build
      run: |
        dotnet restore
        dotnet build --configuration Release --no-restore

    - name: Publish API
      run: dotnet publish ./api-pipelining-practice-project/api-pipelining-practice-project.csproj -c Release -o ./publish --runtime win-x86 --self-contained false

    - name: Deploy via MSDeploy (Native)
      shell: cmd
      run: |
        "C:\Program Files\iis\Microsoft Web Deploy V3\msdeploy.exe" ^
        -verb:sync ^
        -source:contentPath="%CD%\publish" ^
        -dest:contentPath="site56641",computerName="${{ secrets.SERVER_COMPUTER_NAME }}",userName="site56641",password="${{ secrets.SERVER_PASSWORD }}",authtype="Basic",includeAcls="False" ^
        -allowUntrusted ^
        -retryAttempts:2 ^
        -verbose